command_timeout = 10000

[directory]
truncate_to_repo=false
truncation_length=-1

[username]
show_always=true

[custom.toolbox]
when = """ test -e /run/.toolboxenv """
command = "echo toolbox"
#prefix = "in "
symbol = "⬢ "
